# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1144, 759)
        mainWindow.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        mainWindow.setPalette(palette)
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.mainPlot = MatplotlibWidget(self.splitter)
        self.mainPlot.setObjectName("mainPlot")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea = QtWidgets.QScrollArea(self.widget1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 908, 1426))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_74 = QtWidgets.QLabel(self.groupBox)
        self.label_74.setObjectName("label_74")
        self.gridLayout.addWidget(self.label_74, 0, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.groupBox)
        self.label_76.setObjectName("label_76")
        self.gridLayout.addWidget(self.label_76, 11, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.groupBox)
        self.label_79.setObjectName("label_79")
        self.gridLayout.addWidget(self.label_79, 13, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.groupBox)
        self.label_78.setObjectName("label_78")
        self.gridLayout.addWidget(self.label_78, 9, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox)
        self.label_75.setObjectName("label_75")
        self.gridLayout.addWidget(self.label_75, 5, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.groupBox)
        self.label_80.setObjectName("label_80")
        self.gridLayout.addWidget(self.label_80, 15, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.groupBox)
        self.label_77.setObjectName("label_77")
        self.gridLayout.addWidget(self.label_77, 7, 0, 1, 1)
        self.label_158 = QtWidgets.QLabel(self.groupBox)
        self.label_158.setObjectName("label_158")
        self.gridLayout.addWidget(self.label_158, 2, 0, 1, 1)
        self.membrane_aux_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.membrane_aux_power_doubleSpinBox.setMaximum(999999999.99)
        self.membrane_aux_power_doubleSpinBox.setObjectName("membrane_aux_power_doubleSpinBox")
        self.gridLayout.addWidget(self.membrane_aux_power_doubleSpinBox, 3, 0, 1, 1)
        self.label_159 = QtWidgets.QLabel(self.groupBox)
        self.label_159.setObjectName("label_159")
        self.gridLayout.addWidget(self.label_159, 3, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.groupBox)
        self.label_87.setObjectName("label_87")
        self.gridLayout.addWidget(self.label_87, 1, 1, 1, 1)
        self.membrane_unit_flow_in_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.membrane_unit_flow_in_doubleSpinBox.setMaximum(999999999.99)
        self.membrane_unit_flow_in_doubleSpinBox.setObjectName("membrane_unit_flow_in_doubleSpinBox")
        self.gridLayout.addWidget(self.membrane_unit_flow_in_doubleSpinBox, 6, 0, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.groupBox)
        self.label_85.setObjectName("label_85")
        self.gridLayout.addWidget(self.label_85, 8, 1, 1, 1)
        self.membrane_number_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.membrane_number_spinBox.setMaximum(999999999)
        self.membrane_number_spinBox.setObjectName("membrane_number_spinBox")
        self.gridLayout.addWidget(self.membrane_number_spinBox, 1, 0, 1, 1)
        self.membrane_unit_flow_out_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.membrane_unit_flow_out_doubleSpinBox.setMaximum(999999999.99)
        self.membrane_unit_flow_out_doubleSpinBox.setObjectName("membrane_unit_flow_out_doubleSpinBox")
        self.gridLayout.addWidget(self.membrane_unit_flow_out_doubleSpinBox, 8, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox)
        self.label_82.setObjectName("label_82")
        self.gridLayout.addWidget(self.label_82, 14, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.groupBox)
        self.label_86.setObjectName("label_86")
        self.gridLayout.addWidget(self.label_86, 6, 1, 1, 1)
        self.desalination_building_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.desalination_building_unitary_cost_doubleSpinBox.setMaximum(999999999.99)
        self.desalination_building_unitary_cost_doubleSpinBox.setObjectName("desalination_building_unitary_cost_doubleSpinBox")
        self.gridLayout.addWidget(self.desalination_building_unitary_cost_doubleSpinBox, 10, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.groupBox)
        self.label_84.setObjectName("label_84")
        self.gridLayout.addWidget(self.label_84, 10, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox)
        self.label_83.setObjectName("label_83")
        self.gridLayout.addWidget(self.label_83, 12, 1, 1, 1)
        self.desalination_building_life_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.desalination_building_life_spinBox.setMinimum(1)
        self.desalination_building_life_spinBox.setMaximum(900)
        self.desalination_building_life_spinBox.setObjectName("desalination_building_life_spinBox")
        self.gridLayout.addWidget(self.desalination_building_life_spinBox, 14, 0, 1, 1)
        self.desalination_building_maintenance_perc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.desalination_building_maintenance_perc_doubleSpinBox.setMaximum(999999999.99)
        self.desalination_building_maintenance_perc_doubleSpinBox.setObjectName("desalination_building_maintenance_perc_doubleSpinBox")
        self.gridLayout.addWidget(self.desalination_building_maintenance_perc_doubleSpinBox, 12, 0, 1, 1)
        self.desalination_building_after_live_investment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.desalination_building_after_live_investment_doubleSpinBox.setMaximum(100.0)
        self.desalination_building_after_live_investment_doubleSpinBox.setObjectName("desalination_building_after_live_investment_doubleSpinBox")
        self.gridLayout.addWidget(self.desalination_building_after_live_investment_doubleSpinBox, 16, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox)
        self.label_81.setObjectName("label_81")
        self.gridLayout.addWidget(self.label_81, 16, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deposit_demand_plot_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.deposit_demand_plot_pushButton.setObjectName("deposit_demand_plot_pushButton")
        self.gridLayout_2.addWidget(self.deposit_demand_plot_pushButton, 5, 0, 1, 1)
        self.label_156 = QtWidgets.QLabel(self.groupBox_2)
        self.label_156.setObjectName("label_156")
        self.gridLayout_2.addWidget(self.label_156, 4, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.groupBox_2)
        self.label_114.setObjectName("label_114")
        self.gridLayout_2.addWidget(self.label_114, 14, 0, 1, 1)
        self.label_149 = QtWidgets.QLabel(self.groupBox_2)
        self.label_149.setObjectName("label_149")
        self.gridLayout_2.addWidget(self.label_149, 3, 1, 1, 1)
        self.deposit_water_price_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.deposit_water_price_pushButton.setObjectName("deposit_water_price_pushButton")
        self.gridLayout_2.addWidget(self.deposit_water_price_pushButton, 7, 0, 1, 1)
        self.label_155 = QtWidgets.QLabel(self.groupBox_2)
        self.label_155.setObjectName("label_155")
        self.gridLayout_2.addWidget(self.label_155, 8, 0, 1, 1)
        self.label_146 = QtWidgets.QLabel(self.groupBox_2)
        self.label_146.setObjectName("label_146")
        self.gridLayout_2.addWidget(self.label_146, 12, 0, 1, 1)
        self.label_148 = QtWidgets.QLabel(self.groupBox_2)
        self.label_148.setObjectName("label_148")
        self.gridLayout_2.addWidget(self.label_148, 0, 0, 1, 1)
        self.label_157 = QtWidgets.QLabel(self.groupBox_2)
        self.label_157.setObjectName("label_157")
        self.gridLayout_2.addWidget(self.label_157, 10, 0, 1, 1)
        self.label_154 = QtWidgets.QLabel(self.groupBox_2)
        self.label_154.setObjectName("label_154")
        self.gridLayout_2.addWidget(self.label_154, 2, 0, 1, 1)
        self.label_186 = QtWidgets.QLabel(self.groupBox_2)
        self.label_186.setObjectName("label_186")
        self.gridLayout_2.addWidget(self.label_186, 6, 0, 1, 1)
        self.label_150 = QtWidgets.QLabel(self.groupBox_2)
        self.label_150.setObjectName("label_150")
        self.gridLayout_2.addWidget(self.label_150, 1, 1, 1, 1)
        self.deposit_life_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.deposit_life_spinBox.setMaximum(99999999)
        self.deposit_life_spinBox.setObjectName("deposit_life_spinBox")
        self.gridLayout_2.addWidget(self.deposit_life_spinBox, 13, 0, 1, 1)
        self.label_147 = QtWidgets.QLabel(self.groupBox_2)
        self.label_147.setObjectName("label_147")
        self.gridLayout_2.addWidget(self.label_147, 13, 1, 1, 1)
        self.deposito_investment_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.deposito_investment_cost_doubleSpinBox.setMaximum(999999999.99)
        self.deposito_investment_cost_doubleSpinBox.setObjectName("deposito_investment_cost_doubleSpinBox")
        self.gridLayout_2.addWidget(self.deposito_investment_cost_doubleSpinBox, 9, 0, 1, 1)
        self.deposit_maintenance_perc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.deposit_maintenance_perc_doubleSpinBox.setMaximum(100.0)
        self.deposit_maintenance_perc_doubleSpinBox.setObjectName("deposit_maintenance_perc_doubleSpinBox")
        self.gridLayout_2.addWidget(self.deposit_maintenance_perc_doubleSpinBox, 11, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.groupBox_2)
        self.label_104.setObjectName("label_104")
        self.gridLayout_2.addWidget(self.label_104, 5, 1, 1, 1)
        self.label_152 = QtWidgets.QLabel(self.groupBox_2)
        self.label_152.setObjectName("label_152")
        self.gridLayout_2.addWidget(self.label_152, 9, 1, 1, 1)
        self.deposit_head_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.deposit_head_doubleSpinBox.setMaximum(999999999.99)
        self.deposit_head_doubleSpinBox.setObjectName("deposit_head_doubleSpinBox")
        self.gridLayout_2.addWidget(self.deposit_head_doubleSpinBox, 1, 0, 1, 1)
        self.label_151 = QtWidgets.QLabel(self.groupBox_2)
        self.label_151.setObjectName("label_151")
        self.gridLayout_2.addWidget(self.label_151, 11, 1, 1, 1)
        self.deposit_capacity_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.deposit_capacity_doubleSpinBox.setMaximum(999999999.0)
        self.deposit_capacity_doubleSpinBox.setObjectName("deposit_capacity_doubleSpinBox")
        self.gridLayout_2.addWidget(self.deposit_capacity_doubleSpinBox, 3, 0, 1, 1)
        self.label_187 = QtWidgets.QLabel(self.groupBox_2)
        self.label_187.setObjectName("label_187")
        self.gridLayout_2.addWidget(self.label_187, 7, 1, 1, 1)
        self.deposit_after_life_investment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.deposit_after_life_investment_doubleSpinBox.setMaximum(999999999.99)
        self.deposit_after_life_investment_doubleSpinBox.setObjectName("deposit_after_life_investment_doubleSpinBox")
        self.gridLayout_2.addWidget(self.deposit_after_life_investment_doubleSpinBox, 15, 0, 1, 1)
        self.label_153 = QtWidgets.QLabel(self.groupBox_2)
        self.label_153.setObjectName("label_153")
        self.gridLayout_2.addWidget(self.label_153, 15, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_244 = QtWidgets.QLabel(self.groupBox_10)
        self.label_244.setObjectName("label_244")
        self.gridLayout_18.addWidget(self.label_244, 2, 0, 1, 1)
        self.label_246 = QtWidgets.QLabel(self.groupBox_10)
        self.label_246.setObjectName("label_246")
        self.gridLayout_18.addWidget(self.label_246, 4, 0, 1, 1)
        self.label_247 = QtWidgets.QLabel(self.groupBox_10)
        self.label_247.setObjectName("label_247")
        self.gridLayout_18.addWidget(self.label_247, 6, 0, 1, 1)
        self.label_248 = QtWidgets.QLabel(self.groupBox_10)
        self.label_248.setObjectName("label_248")
        self.gridLayout_18.addWidget(self.label_248, 10, 0, 1, 1)
        self.label_250 = QtWidgets.QLabel(self.groupBox_10)
        self.label_250.setObjectName("label_250")
        self.gridLayout_18.addWidget(self.label_250, 12, 0, 1, 1)
        self.label_253 = QtWidgets.QLabel(self.groupBox_10)
        self.label_253.setObjectName("label_253")
        self.gridLayout_18.addWidget(self.label_253, 8, 0, 1, 1)
        self.label_256 = QtWidgets.QLabel(self.groupBox_10)
        self.label_256.setObjectName("label_256")
        self.gridLayout_18.addWidget(self.label_256, 0, 0, 1, 1)
        self.label_252 = QtWidgets.QLabel(self.groupBox_10)
        self.label_252.setObjectName("label_252")
        self.gridLayout_18.addWidget(self.label_252, 3, 1, 1, 1)
        self.sea_pump_nominal_flow_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.sea_pump_nominal_flow_doubleSpinBox.setMaximum(999999999.0)
        self.sea_pump_nominal_flow_doubleSpinBox.setObjectName("sea_pump_nominal_flow_doubleSpinBox")
        self.gridLayout_18.addWidget(self.sea_pump_nominal_flow_doubleSpinBox, 5, 0, 1, 1)
        self.sea_pump_maintenance_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.sea_pump_maintenance_cost_doubleSpinBox.setMaximum(100.0)
        self.sea_pump_maintenance_cost_doubleSpinBox.setObjectName("sea_pump_maintenance_cost_doubleSpinBox")
        self.gridLayout_18.addWidget(self.sea_pump_maintenance_cost_doubleSpinBox, 9, 0, 1, 1)
        self.label_251 = QtWidgets.QLabel(self.groupBox_10)
        self.label_251.setObjectName("label_251")
        self.gridLayout_18.addWidget(self.label_251, 1, 1, 1, 1)
        self.sea_pump_life_spinBox = QtWidgets.QSpinBox(self.groupBox_10)
        self.sea_pump_life_spinBox.setMaximum(999999999)
        self.sea_pump_life_spinBox.setObjectName("sea_pump_life_spinBox")
        self.gridLayout_18.addWidget(self.sea_pump_life_spinBox, 11, 0, 1, 1)
        self.label_245 = QtWidgets.QLabel(self.groupBox_10)
        self.label_245.setObjectName("label_245")
        self.gridLayout_18.addWidget(self.label_245, 11, 1, 1, 1)
        self.sea_pump_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.sea_pump_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.sea_pump_unitary_cost_doubleSpinBox.setObjectName("sea_pump_unitary_cost_doubleSpinBox")
        self.gridLayout_18.addWidget(self.sea_pump_unitary_cost_doubleSpinBox, 7, 0, 1, 1)
        self.label_255 = QtWidgets.QLabel(self.groupBox_10)
        self.label_255.setObjectName("label_255")
        self.gridLayout_18.addWidget(self.label_255, 5, 1, 1, 1)
        self.sea_pump_nominal_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.sea_pump_nominal_power_doubleSpinBox.setMaximum(999999999.0)
        self.sea_pump_nominal_power_doubleSpinBox.setObjectName("sea_pump_nominal_power_doubleSpinBox")
        self.gridLayout_18.addWidget(self.sea_pump_nominal_power_doubleSpinBox, 3, 0, 1, 1)
        self.sea_pump_units_spinBox = QtWidgets.QSpinBox(self.groupBox_10)
        self.sea_pump_units_spinBox.setMaximum(999999999)
        self.sea_pump_units_spinBox.setObjectName("sea_pump_units_spinBox")
        self.gridLayout_18.addWidget(self.sea_pump_units_spinBox, 1, 0, 1, 1)
        self.label_257 = QtWidgets.QLabel(self.groupBox_10)
        self.label_257.setObjectName("label_257")
        self.gridLayout_18.addWidget(self.label_257, 9, 1, 1, 1)
        self.label_249 = QtWidgets.QLabel(self.groupBox_10)
        self.label_249.setObjectName("label_249")
        self.gridLayout_18.addWidget(self.label_249, 7, 1, 1, 1)
        self.sea_pump_after_life_investent_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.sea_pump_after_life_investent_doubleSpinBox.setMaximum(100.0)
        self.sea_pump_after_life_investent_doubleSpinBox.setObjectName("sea_pump_after_life_investent_doubleSpinBox")
        self.gridLayout_18.addWidget(self.sea_pump_after_life_investent_doubleSpinBox, 13, 0, 1, 1)
        self.label_254 = QtWidgets.QLabel(self.groupBox_10)
        self.label_254.setObjectName("label_254")
        self.gridLayout_18.addWidget(self.label_254, 13, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.scrollArea)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/file/ic_insert_chart_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.widget1, icon, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_8)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -191, 928, 698))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.solar_enable_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.solar_enable_checkBox.setObjectName("solar_enable_checkBox")
        self.verticalLayout.addWidget(self.solar_enable_checkBox)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.solar_plot_irradiation_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.solar_plot_irradiation_pushButton.setObjectName("solar_plot_irradiation_pushButton")
        self.gridLayout_17.addWidget(self.solar_plot_irradiation_pushButton, 1, 0, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.groupBox_9)
        self.label_92.setObjectName("label_92")
        self.gridLayout_17.addWidget(self.label_92, 6, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.groupBox_9)
        self.label_89.setObjectName("label_89")
        self.gridLayout_17.addWidget(self.label_89, 2, 0, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.groupBox_9)
        self.label_94.setObjectName("label_94")
        self.gridLayout_17.addWidget(self.label_94, 12, 0, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.groupBox_9)
        self.label_90.setObjectName("label_90")
        self.gridLayout_17.addWidget(self.label_90, 8, 0, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.groupBox_9)
        self.label_91.setObjectName("label_91")
        self.gridLayout_17.addWidget(self.label_91, 4, 0, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.groupBox_9)
        self.label_93.setObjectName("label_93")
        self.gridLayout_17.addWidget(self.label_93, 10, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.groupBox_9)
        self.label_88.setObjectName("label_88")
        self.gridLayout_17.addWidget(self.label_88, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem, 24, 0, 1, 3)
        self.label_130 = QtWidgets.QLabel(self.groupBox_9)
        self.label_130.setObjectName("label_130")
        self.gridLayout_17.addWidget(self.label_130, 15, 0, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.groupBox_9)
        self.label_131.setObjectName("label_131")
        self.gridLayout_17.addWidget(self.label_131, 17, 0, 1, 1)
        self.solar_life_span_spinBox = QtWidgets.QSpinBox(self.groupBox_9)
        self.solar_life_span_spinBox.setObjectName("solar_life_span_spinBox")
        self.gridLayout_17.addWidget(self.solar_life_span_spinBox, 11, 0, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.groupBox_9)
        self.label_95.setObjectName("label_95")
        self.gridLayout_17.addWidget(self.label_95, 13, 1, 1, 1)
        self.solar_panel_size_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_panel_size_doubleSpinBox.setProperty("value", 1.5)
        self.solar_panel_size_doubleSpinBox.setObjectName("solar_panel_size_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_panel_size_doubleSpinBox, 3, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.groupBox_9)
        self.label_96.setObjectName("label_96")
        self.gridLayout_17.addWidget(self.label_96, 11, 1, 1, 1)
        self.solar_panel_eff_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_panel_eff_doubleSpinBox.setMaximum(1.0)
        self.solar_panel_eff_doubleSpinBox.setProperty("value", 0.2)
        self.solar_panel_eff_doubleSpinBox.setObjectName("solar_panel_eff_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_panel_eff_doubleSpinBox, 5, 0, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.groupBox_9)
        self.label_101.setObjectName("label_101")
        self.gridLayout_17.addWidget(self.label_101, 1, 1, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.groupBox_9)
        self.label_99.setObjectName("label_99")
        self.gridLayout_17.addWidget(self.label_99, 5, 1, 1, 1)
        self.solar_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.solar_unitary_cost_doubleSpinBox.setObjectName("solar_unitary_cost_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_unitary_cost_doubleSpinBox, 7, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.groupBox_9)
        self.label_100.setObjectName("label_100")
        self.gridLayout_17.addWidget(self.label_100, 3, 1, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.groupBox_9)
        self.label_97.setObjectName("label_97")
        self.gridLayout_17.addWidget(self.label_97, 9, 1, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.groupBox_9)
        self.label_132.setObjectName("label_132")
        self.gridLayout_17.addWidget(self.label_132, 16, 1, 1, 1)
        self.solar_maintenance_perc_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_maintenance_perc_cost_doubleSpinBox.setMaximum(999999999.0)
        self.solar_maintenance_perc_cost_doubleSpinBox.setObjectName("solar_maintenance_perc_cost_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_maintenance_perc_cost_doubleSpinBox, 9, 0, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.groupBox_9)
        self.label_98.setObjectName("label_98")
        self.gridLayout_17.addWidget(self.label_98, 7, 1, 1, 1)
        self.solar_after_life_investment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_after_life_investment_doubleSpinBox.setObjectName("solar_after_life_investment_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_after_life_investment_doubleSpinBox, 13, 0, 1, 1)
        self.solar_min_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_min_power_doubleSpinBox.setMaximum(999999999.0)
        self.solar_min_power_doubleSpinBox.setProperty("value", 0.0)
        self.solar_min_power_doubleSpinBox.setObjectName("solar_min_power_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_min_power_doubleSpinBox, 16, 0, 1, 1)
        self.solar_max_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_max_power_doubleSpinBox.setMaximum(999999999.0)
        self.solar_max_power_doubleSpinBox.setProperty("value", 0.0)
        self.solar_max_power_doubleSpinBox.setObjectName("solar_max_power_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_max_power_doubleSpinBox, 18, 0, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.groupBox_9)
        self.label_133.setObjectName("label_133")
        self.gridLayout_17.addWidget(self.label_133, 18, 1, 1, 1)
        self.label_161 = QtWidgets.QLabel(self.groupBox_9)
        self.label_161.setObjectName("label_161")
        self.gridLayout_17.addWidget(self.label_161, 19, 0, 1, 1)
        self.solar_land_usage_rate_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_land_usage_rate_doubleSpinBox.setDecimals(10)
        self.solar_land_usage_rate_doubleSpinBox.setMaximum(999999999.0)
        self.solar_land_usage_rate_doubleSpinBox.setProperty("value", 0.000335)
        self.solar_land_usage_rate_doubleSpinBox.setObjectName("solar_land_usage_rate_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_land_usage_rate_doubleSpinBox, 20, 0, 1, 1)
        self.label_160 = QtWidgets.QLabel(self.groupBox_9)
        self.label_160.setObjectName("label_160")
        self.gridLayout_17.addWidget(self.label_160, 20, 1, 1, 1)
        self.solar_land_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.solar_land_cost_doubleSpinBox.setMaximum(999999999.0)
        self.solar_land_cost_doubleSpinBox.setProperty("value", 100000.0)
        self.solar_land_cost_doubleSpinBox.setObjectName("solar_land_cost_doubleSpinBox")
        self.gridLayout_17.addWidget(self.solar_land_cost_doubleSpinBox, 23, 0, 1, 1)
        self.label_163 = QtWidgets.QLabel(self.groupBox_9)
        self.label_163.setObjectName("label_163")
        self.gridLayout_17.addWidget(self.label_163, 21, 0, 1, 1)
        self.label_162 = QtWidgets.QLabel(self.groupBox_9)
        self.label_162.setObjectName("label_162")
        self.gridLayout_17.addWidget(self.label_162, 23, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_9)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, -99, 928, 606))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.wind_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.wind_unitary_cost_doubleSpinBox.setObjectName("wind_unitary_cost_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_unitary_cost_doubleSpinBox, 6, 0, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_107.setObjectName("label_107")
        self.gridLayout_8.addWidget(self.label_107, 6, 1, 1, 1)
        self.wind_life_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_life_spinBox.setMaximum(999999999)
        self.wind_life_spinBox.setObjectName("wind_life_spinBox")
        self.gridLayout_8.addWidget(self.wind_life_spinBox, 10, 0, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_115.setObjectName("label_115")
        self.gridLayout_8.addWidget(self.label_115, 4, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_108.setObjectName("label_108")
        self.gridLayout_8.addWidget(self.label_108, 2, 1, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_106.setObjectName("label_106")
        self.gridLayout_8.addWidget(self.label_106, 1, 0, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_109.setObjectName("label_109")
        self.gridLayout_8.addWidget(self.label_109, 7, 0, 1, 1)
        self.wind_turbine_curve_plot_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.wind_turbine_curve_plot_pushButton.setObjectName("wind_turbine_curve_plot_pushButton")
        self.gridLayout_8.addWidget(self.wind_turbine_curve_plot_pushButton, 4, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_105.setObjectName("label_105")
        self.gridLayout_8.addWidget(self.label_105, 11, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_103.setObjectName("label_103")
        self.gridLayout_8.addWidget(self.label_103, 12, 1, 1, 1)
        self.label_140 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_140.setObjectName("label_140")
        self.gridLayout_8.addWidget(self.label_140, 13, 0, 1, 1)
        self.wind_after_life_investment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_after_life_investment_doubleSpinBox.setMaximum(100.0)
        self.wind_after_life_investment_doubleSpinBox.setObjectName("wind_after_life_investment_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_after_life_investment_doubleSpinBox, 12, 0, 1, 1)
        self.wind_maintenance_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_maintenance_cost_doubleSpinBox.setMaximum(100.0)
        self.wind_maintenance_cost_doubleSpinBox.setObjectName("wind_maintenance_cost_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_maintenance_cost_doubleSpinBox, 8, 0, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_110.setObjectName("label_110")
        self.gridLayout_8.addWidget(self.label_110, 9, 0, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_111.setObjectName("label_111")
        self.gridLayout_8.addWidget(self.label_111, 5, 0, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_112.setObjectName("label_112")
        self.gridLayout_8.addWidget(self.label_112, 10, 1, 1, 1)
        self.wind_speed_plot_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.wind_speed_plot_pushButton.setObjectName("wind_speed_plot_pushButton")
        self.gridLayout_8.addWidget(self.wind_speed_plot_pushButton, 2, 0, 1, 1)
        self.wind_max_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_max_power_doubleSpinBox.setMaximum(999999999.0)
        self.wind_max_power_doubleSpinBox.setProperty("value", 0.0)
        self.wind_max_power_doubleSpinBox.setObjectName("wind_max_power_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_max_power_doubleSpinBox, 16, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_102.setObjectName("label_102")
        self.gridLayout_8.addWidget(self.label_102, 8, 1, 1, 1)
        self.wind_min_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_min_power_doubleSpinBox.setMaximum(999999999.0)
        self.wind_min_power_doubleSpinBox.setProperty("value", 0.0)
        self.wind_min_power_doubleSpinBox.setObjectName("wind_min_power_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_min_power_doubleSpinBox, 14, 0, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_138.setObjectName("label_138")
        self.gridLayout_8.addWidget(self.label_138, 16, 1, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_134.setObjectName("label_134")
        self.gridLayout_8.addWidget(self.label_134, 15, 0, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_113.setObjectName("label_113")
        self.gridLayout_8.addWidget(self.label_113, 3, 0, 1, 1)
        self.wind_enable_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.wind_enable_checkBox.setObjectName("wind_enable_checkBox")
        self.gridLayout_8.addWidget(self.wind_enable_checkBox, 0, 0, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_137.setObjectName("label_137")
        self.gridLayout_8.addWidget(self.label_137, 14, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 21, 0, 1, 1)
        self.label_164 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_164.setObjectName("label_164")
        self.gridLayout_8.addWidget(self.label_164, 17, 0, 1, 1)
        self.label_166 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_166.setObjectName("label_166")
        self.gridLayout_8.addWidget(self.label_166, 19, 0, 1, 1)
        self.wind_land_usage_rate_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_land_usage_rate_doubleSpinBox.setDecimals(10)
        self.wind_land_usage_rate_doubleSpinBox.setMaximum(999999999.0)
        self.wind_land_usage_rate_doubleSpinBox.setProperty("value", 2e-06)
        self.wind_land_usage_rate_doubleSpinBox.setObjectName("wind_land_usage_rate_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_land_usage_rate_doubleSpinBox, 18, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_165.setObjectName("label_165")
        self.gridLayout_8.addWidget(self.label_165, 18, 1, 1, 1)
        self.wind_land_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.wind_land_cost_doubleSpinBox.setDecimals(10)
        self.wind_land_cost_doubleSpinBox.setMaximum(999999999.0)
        self.wind_land_cost_doubleSpinBox.setProperty("value", 2e-06)
        self.wind_land_cost_doubleSpinBox.setObjectName("wind_land_cost_doubleSpinBox")
        self.gridLayout_8.addWidget(self.wind_land_cost_doubleSpinBox, 20, 0, 1, 1)
        self.label_167 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_167.setObjectName("label_167")
        self.gridLayout_8.addWidget(self.label_167, 20, 1, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_7.addWidget(self.scrollArea_4)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_10)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -205, 928, 712))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_118 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_118.setObjectName("label_118")
        self.gridLayout_12.addWidget(self.label_118, 15, 2, 1, 1)
        self.storage_max_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_max_power_doubleSpinBox.setMaximum(999999999.0)
        self.storage_max_power_doubleSpinBox.setProperty("value", 0.0)
        self.storage_max_power_doubleSpinBox.setObjectName("storage_max_power_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_max_power_doubleSpinBox, 21, 1, 1, 1)
        self.storage_maintenance_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_maintenance_cost_doubleSpinBox.setMaximum(100.0)
        self.storage_maintenance_cost_doubleSpinBox.setObjectName("storage_maintenance_cost_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_maintenance_cost_doubleSpinBox, 9, 1, 1, 1)
        self.storage_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.storage_unitary_cost_doubleSpinBox.setObjectName("storage_unitary_cost_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_unitary_cost_doubleSpinBox, 7, 1, 1, 1)
        self.label_126 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_126.setObjectName("label_126")
        self.gridLayout_12.addWidget(self.label_126, 11, 2, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_128.setObjectName("label_128")
        self.gridLayout_12.addWidget(self.label_128, 14, 1, 1, 1)
        self.storage_min_soc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_min_soc_doubleSpinBox.setMaximum(100.0)
        self.storage_min_soc_doubleSpinBox.setProperty("value", 100.0)
        self.storage_min_soc_doubleSpinBox.setObjectName("storage_min_soc_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_min_soc_doubleSpinBox, 17, 1, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_116.setObjectName("label_116")
        self.gridLayout_12.addWidget(self.label_116, 9, 2, 1, 1)
        self.storage_discharge_eff_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_discharge_eff_doubleSpinBox.setMaximum(100.0)
        self.storage_discharge_eff_doubleSpinBox.setProperty("value", 100.0)
        self.storage_discharge_eff_doubleSpinBox.setObjectName("storage_discharge_eff_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_discharge_eff_doubleSpinBox, 15, 1, 1, 1)
        self.storage_max_soc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_max_soc_doubleSpinBox.setMaximum(100.0)
        self.storage_max_soc_doubleSpinBox.setProperty("value", 0.0)
        self.storage_max_soc_doubleSpinBox.setObjectName("storage_max_soc_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_max_soc_doubleSpinBox, 5, 1, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_120.setObjectName("label_120")
        self.gridLayout_12.addWidget(self.label_120, 2, 1, 1, 1)
        self.label_145 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_145.setObjectName("label_145")
        self.gridLayout_12.addWidget(self.label_145, 17, 2, 1, 1)
        self.storage_life_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_life_spinBox.setMaximum(999999999)
        self.storage_life_spinBox.setObjectName("storage_life_spinBox")
        self.gridLayout_12.addWidget(self.storage_life_spinBox, 11, 1, 1, 1)
        self.storage_charge_eff_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_charge_eff_doubleSpinBox.setMaximum(100.0)
        self.storage_charge_eff_doubleSpinBox.setProperty("value", 100.0)
        self.storage_charge_eff_doubleSpinBox.setObjectName("storage_charge_eff_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_charge_eff_doubleSpinBox, 3, 1, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_127.setObjectName("label_127")
        self.gridLayout_12.addWidget(self.label_127, 4, 1, 1, 1)
        self.label_144 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_144.setObjectName("label_144")
        self.gridLayout_12.addWidget(self.label_144, 16, 1, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_122.setObjectName("label_122")
        self.gridLayout_12.addWidget(self.label_122, 3, 2, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_124.setObjectName("label_124")
        self.gridLayout_12.addWidget(self.label_124, 10, 1, 1, 1)
        self.label_172 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_172.setObjectName("label_172")
        self.gridLayout_12.addWidget(self.label_172, 20, 1, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_129.setObjectName("label_129")
        self.gridLayout_12.addWidget(self.label_129, 5, 2, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_119.setObjectName("label_119")
        self.gridLayout_12.addWidget(self.label_119, 12, 1, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_117.setObjectName("label_117")
        self.gridLayout_12.addWidget(self.label_117, 13, 2, 1, 1)
        self.storage_after_life_investment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_after_life_investment_doubleSpinBox.setObjectName("storage_after_life_investment_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_after_life_investment_doubleSpinBox, 13, 1, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_123.setObjectName("label_123")
        self.gridLayout_12.addWidget(self.label_123, 8, 1, 1, 1)
        self.storage_min_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_min_power_doubleSpinBox.setMaximum(999999999.0)
        self.storage_min_power_doubleSpinBox.setProperty("value", 0.0)
        self.storage_min_power_doubleSpinBox.setObjectName("storage_min_power_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_min_power_doubleSpinBox, 19, 1, 1, 1)
        self.label_175 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_175.setObjectName("label_175")
        self.gridLayout_12.addWidget(self.label_175, 19, 2, 1, 1)
        self.label_125 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_125.setObjectName("label_125")
        self.gridLayout_12.addWidget(self.label_125, 6, 1, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_121.setObjectName("label_121")
        self.gridLayout_12.addWidget(self.label_121, 7, 2, 1, 1)
        self.label_174 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_174.setObjectName("label_174")
        self.gridLayout_12.addWidget(self.label_174, 21, 2, 1, 1)
        self.label_173 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_173.setObjectName("label_173")
        self.gridLayout_12.addWidget(self.label_173, 18, 1, 1, 1)
        self.storage_enable_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.storage_enable_checkBox.setObjectName("storage_enable_checkBox")
        self.gridLayout_12.addWidget(self.storage_enable_checkBox, 1, 1, 1, 1)
        self.storage_land_usage_rate_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_land_usage_rate_doubleSpinBox.setMaximum(999999999.0)
        self.storage_land_usage_rate_doubleSpinBox.setProperty("value", 0.0)
        self.storage_land_usage_rate_doubleSpinBox.setObjectName("storage_land_usage_rate_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_land_usage_rate_doubleSpinBox, 23, 1, 1, 1)
        self.label_178 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_178.setObjectName("label_178")
        self.gridLayout_12.addWidget(self.label_178, 24, 1, 1, 1)
        self.label_177 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_177.setObjectName("label_177")
        self.gridLayout_12.addWidget(self.label_177, 23, 2, 1, 1)
        self.label_176 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_176.setObjectName("label_176")
        self.gridLayout_12.addWidget(self.label_176, 22, 1, 1, 1)
        self.storage_land_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.storage_land_cost_doubleSpinBox.setMaximum(999999999.0)
        self.storage_land_cost_doubleSpinBox.setProperty("value", 0.0)
        self.storage_land_cost_doubleSpinBox.setObjectName("storage_land_cost_doubleSpinBox")
        self.gridLayout_12.addWidget(self.storage_land_cost_doubleSpinBox, 25, 1, 1, 1)
        self.label_179 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_179.setObjectName("label_179")
        self.gridLayout_12.addWidget(self.label_179, 25, 2, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_3)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_143 = QtWidgets.QLabel(self.tab_11)
        self.label_143.setObjectName("label_143")
        self.gridLayout_5.addWidget(self.label_143, 2, 1, 1, 1)
        self.grid_connection_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_11)
        self.grid_connection_power_doubleSpinBox.setMaximum(999999999.0)
        self.grid_connection_power_doubleSpinBox.setObjectName("grid_connection_power_doubleSpinBox")
        self.gridLayout_5.addWidget(self.grid_connection_power_doubleSpinBox, 2, 0, 1, 1)
        self.label_142 = QtWidgets.QLabel(self.tab_11)
        self.label_142.setObjectName("label_142")
        self.gridLayout_5.addWidget(self.label_142, 3, 0, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.tab_11)
        self.label_136.setObjectName("label_136")
        self.gridLayout_5.addWidget(self.label_136, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 7, 0, 1, 1)
        self.secondary_price_plot_pushButton = QtWidgets.QPushButton(self.tab_11)
        self.secondary_price_plot_pushButton.setObjectName("secondary_price_plot_pushButton")
        self.gridLayout_5.addWidget(self.secondary_price_plot_pushButton, 6, 0, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.tab_11)
        self.label_135.setObjectName("label_135")
        self.gridLayout_5.addWidget(self.label_135, 6, 1, 1, 1)
        self.label_139 = QtWidgets.QLabel(self.tab_11)
        self.label_139.setObjectName("label_139")
        self.gridLayout_5.addWidget(self.label_139, 5, 0, 1, 1)
        self.grid_enable_checkBox = QtWidgets.QCheckBox(self.tab_11)
        self.grid_enable_checkBox.setObjectName("grid_enable_checkBox")
        self.gridLayout_5.addWidget(self.grid_enable_checkBox, 0, 0, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.tab_11)
        self.label_141.setObjectName("label_141")
        self.gridLayout_5.addWidget(self.label_141, 1, 0, 1, 1)
        self.spot_price_pushButton = QtWidgets.QPushButton(self.tab_11)
        self.spot_price_pushButton.setObjectName("spot_price_pushButton")
        self.gridLayout_5.addWidget(self.spot_price_pushButton, 4, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.gridLayout_16.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.widget, icon, "")
        self.SimulationTab = QtWidgets.QWidget()
        self.SimulationTab.setObjectName("SimulationTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.SimulationTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.splitter_2 = QtWidgets.QSplitter(self.SimulationTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_6 = QtWidgets.QFrame(self.splitter_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_29 = QtWidgets.QLabel(self.groupBox_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 0, 2, 1, 1)
        self.max_eval_spinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.max_eval_spinBox.setMinimum(10)
        self.max_eval_spinBox.setMaximum(99999999)
        self.max_eval_spinBox.setProperty("value", 100)
        self.max_eval_spinBox.setObjectName("max_eval_spinBox")
        self.gridLayout_7.addWidget(self.max_eval_spinBox, 1, 1, 1, 1)
        self.size_simulate_pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.size_simulate_pushButton.setObjectName("size_simulate_pushButton")
        self.gridLayout_7.addWidget(self.size_simulate_pushButton, 1, 0, 1, 1)
        self.obj_function_comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.obj_function_comboBox.setObjectName("obj_function_comboBox")
        self.gridLayout_7.addWidget(self.obj_function_comboBox, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 0, 1, 1, 1)
        self.start_dateEdit = QtWidgets.QDateEdit(self.groupBox_6)
        self.start_dateEdit.setObjectName("start_dateEdit")
        self.gridLayout_7.addWidget(self.start_dateEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 0, 0, 1, 2)
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.results_tableView = QtWidgets.QTableView(self.groupBox_21)
        self.results_tableView.setAlternatingRowColors(True)
        self.results_tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.results_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.results_tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.results_tableView.setSortingEnabled(False)
        self.results_tableView.setObjectName("results_tableView")
        self.gridLayout_4.addWidget(self.results_tableView, 2, 0, 1, 2)
        self.analyze_selected_pushButton = QtWidgets.QPushButton(self.groupBox_21)
        self.analyze_selected_pushButton.setObjectName("analyze_selected_pushButton")
        self.gridLayout_4.addWidget(self.analyze_selected_pushButton, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_21, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.splitter_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.results_comboBox = QtWidgets.QComboBox(self.tab)
        self.results_comboBox.setObjectName("results_comboBox")
        self.gridLayout_11.addWidget(self.results_comboBox, 0, 0, 1, 1)
        self.resultsPlot = MatplotlibWidget(self.tab)
        self.resultsPlot.setObjectName("resultsPlot")
        self.gridLayout_11.addWidget(self.resultsPlot, 2, 0, 1, 2)
        self.plot_results_pushButton = QtWidgets.QPushButton(self.tab)
        self.plot_results_pushButton.setObjectName("plot_results_pushButton")
        self.gridLayout_11.addWidget(self.plot_results_pushButton, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_11.addWidget(self.plainTextEdit)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_12.addWidget(self.label_36)
        self.economic_tableView = QtWidgets.QTableView(self.tab_3)
        self.economic_tableView.setAlternatingRowColors(True)
        self.economic_tableView.setObjectName("economic_tableView")
        self.verticalLayout_12.addWidget(self.economic_tableView)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cash_flow_tableView = QtWidgets.QTableView(self.tab_4)
        self.cash_flow_tableView.setAlternatingRowColors(True)
        self.cash_flow_tableView.setObjectName("cash_flow_tableView")
        self.horizontalLayout.addWidget(self.cash_flow_tableView)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_8.addWidget(self.tabWidget_2)
        self.verticalLayout_10.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.SimulationTab, "")
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.progress_frame = QtWidgets.QFrame(self.centralwidget)
        self.progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_frame.setObjectName("progress_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.progress_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.progress_label = QtWidgets.QLabel(self.progress_frame)
        self.progress_label.setObjectName("progress_label")
        self.gridLayout_6.addWidget(self.progress_label, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.progress_frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_6.addWidget(self.progressBar, 1, 0, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(self.progress_frame)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout_6.addWidget(self.cancel_pushButton, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.progress_frame, 1, 0, 1, 1)
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.gridLayout_9.addWidget(self.info_label, 2, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1144, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuProject = QtWidgets.QMenu(self.menuBar)
        self.menuProject.setObjectName("menuProject")
        mainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_file = QtWidgets.QAction(mainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew_project = QtWidgets.QAction(mainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDiagram = QtWidgets.QAction(mainWindow)
        self.actionDiagram.setObjectName("actionDiagram")
        self.menuProject.addAction(self.actionNew_project)
        self.menuProject.addAction(self.actionOpen_file)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addSeparator()
        self.menuBar.addAction(self.menuProject.menuAction())
        self.toolBar.addAction(self.actionOpen_file)
        self.toolBar.addAction(self.actionSave)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Desalination plant"))
        self.groupBox.setTitle(_translate("mainWindow", "Membranes"))
        self.label_74.setText(_translate("mainWindow", "Membrane pack"))
        self.label_76.setText(_translate("mainWindow", "Maintenence cost as % of the investment cost"))
        self.label_79.setText(_translate("mainWindow", "Equipement life"))
        self.label_78.setText(_translate("mainWindow", "Cost per installed kW"))
        self.label_75.setText(_translate("mainWindow", "Water flow in"))
        self.label_80.setText(_translate("mainWindow", "Percentaje of the investment cost to incurr once the live span has passed"))
        self.label_77.setText(_translate("mainWindow", "Water flow out"))
        self.label_158.setText(_translate("mainWindow", "Axiliaries power"))
        self.label_159.setText(_translate("mainWindow", "kW"))
        self.label_87.setText(_translate("mainWindow", "Units"))
        self.label_85.setText(_translate("mainWindow", "m3/h"))
        self.label_82.setText(_translate("mainWindow", "Years"))
        self.label_86.setText(_translate("mainWindow", "m3/h"))
        self.label_84.setText(_translate("mainWindow", "€/kW"))
        self.label_83.setText(_translate("mainWindow", "%"))
        self.label_81.setText(_translate("mainWindow", "%"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Water storage deposit"))
        self.deposit_demand_plot_pushButton.setText(_translate("mainWindow", "Plot"))
        self.label_156.setText(_translate("mainWindow", "Water demand profile"))
        self.label_114.setText(_translate("mainWindow", "Percentaje of the investment cost to incurr once the live span has passed"))
        self.label_149.setText(_translate("mainWindow", "m3"))
        self.deposit_water_price_pushButton.setText(_translate("mainWindow", "Plot"))
        self.label_155.setText(_translate("mainWindow", "Investment cost"))
        self.label_146.setText(_translate("mainWindow", "Equipement life"))
        self.label_148.setText(_translate("mainWindow", "Relative head"))
        self.label_157.setText(_translate("mainWindow", "Maintenence cost as % of the investment cost"))
        self.label_154.setText(_translate("mainWindow", "Storage capacity"))
        self.label_186.setText(_translate("mainWindow", "Water price profile"))
        self.label_150.setText(_translate("mainWindow", "m"))
        self.label_147.setText(_translate("mainWindow", "Years"))
        self.label_104.setText(_translate("mainWindow", "m3"))
        self.label_152.setText(_translate("mainWindow", "€/kWh"))
        self.label_151.setText(_translate("mainWindow", "%"))
        self.label_187.setText(_translate("mainWindow", "€/m3"))
        self.label_153.setText(_translate("mainWindow", "%"))
        self.groupBox_10.setTitle(_translate("mainWindow", "Sea - Plant pump group"))
        self.label_244.setText(_translate("mainWindow", "Nominal power"))
        self.label_246.setText(_translate("mainWindow", "Nominal flow"))
        self.label_247.setText(_translate("mainWindow", "Cost per installed kW"))
        self.label_248.setText(_translate("mainWindow", "Equipement life"))
        self.label_250.setText(_translate("mainWindow", "Percentaje of the investment cost to incurr once the live span has passed"))
        self.label_253.setText(_translate("mainWindow", "Maintenence cost as % of the investment cost"))
        self.label_256.setText(_translate("mainWindow", "Number of pumps"))
        self.label_252.setText(_translate("mainWindow", "kW"))
        self.label_251.setText(_translate("mainWindow", "units"))
        self.label_245.setText(_translate("mainWindow", "Years"))
        self.label_255.setText(_translate("mainWindow", "m3/h"))
        self.label_257.setText(_translate("mainWindow", "%"))
        self.label_249.setText(_translate("mainWindow", "€/kWh"))
        self.label_254.setText(_translate("mainWindow", "%"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.widget1), _translate("mainWindow", "Desalination plant"))
        self.solar_enable_checkBox.setText(_translate("mainWindow", "Enabled"))
        self.groupBox_9.setTitle(_translate("mainWindow", "Solar plant"))
        self.solar_plot_irradiation_pushButton.setText(_translate("mainWindow", "Plot"))
        self.label_92.setText(_translate("mainWindow", "Cost per installed kW"))
        self.label_89.setText(_translate("mainWindow", "Size of the solar panel to use"))
        self.label_94.setText(_translate("mainWindow", "Percentaje of the investment cost to incurr once the live span has passed"))
        self.label_90.setText(_translate("mainWindow", "Maintenence cost as % of the investment cost"))
        self.label_91.setText(_translate("mainWindow", "Efficiency of the panel"))
        self.label_93.setText(_translate("mainWindow", "Equipement life"))
        self.label_88.setText(_translate("mainWindow", "Yearly irradiation profile"))
        self.label_130.setText(_translate("mainWindow", "Minimum power for sizing"))
        self.label_131.setText(_translate("mainWindow", "Maximum power for sizing"))
        self.label_95.setText(_translate("mainWindow", "%"))
        self.label_96.setText(_translate("mainWindow", "Years"))
        self.label_101.setText(_translate("mainWindow", "W/m^2"))
        self.label_99.setText(_translate("mainWindow", "per unit"))
        self.label_100.setText(_translate("mainWindow", "m^2"))
        self.label_97.setText(_translate("mainWindow", "%"))
        self.label_132.setText(_translate("mainWindow", "kW"))
        self.label_98.setText(_translate("mainWindow", "€/kW"))
        self.label_133.setText(_translate("mainWindow", "kW"))
        self.label_161.setText(_translate("mainWindow", "Land usage rate"))
        self.label_160.setText(_translate("mainWindow", "km^2 / kW"))
        self.label_163.setText(_translate("mainWindow", "Land cost"))
        self.label_162.setText(_translate("mainWindow", "€ / km^2"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("mainWindow", "Solar plant"))
        self.label_107.setText(_translate("mainWindow", "€/kW"))
        self.label_115.setText(_translate("mainWindow", "kW"))
        self.label_108.setText(_translate("mainWindow", "m/s"))
        self.label_106.setText(_translate("mainWindow", "Yearly profile of wind speed"))
        self.label_109.setText(_translate("mainWindow", "Maintenence cost as % of the investment cost"))
        self.wind_turbine_curve_plot_pushButton.setText(_translate("mainWindow", "Plot"))
        self.label_105.setText(_translate("mainWindow", "Percentaje of the investment cost to incurr once the live span has passed"))
        self.label_103.setText(_translate("mainWindow", "%"))
        self.label_140.setText(_translate("mainWindow", "Minimum power for sizing"))
        self.label_110.setText(_translate("mainWindow", "Equipement life"))
        self.label_111.setText(_translate("mainWindow", "Cost per installed kW"))
        self.label_112.setText(_translate("mainWindow", "Years"))
        self.wind_speed_plot_pushButton.setText(_translate("mainWindow", "Plot"))
        self.label_102.setText(_translate("mainWindow", "%"))
        self.label_138.setText(_translate("mainWindow", "kW"))
        self.label_134.setText(_translate("mainWindow", "Maximum power for sizing"))
        self.label_113.setText(_translate("mainWindow", "Wind turbine curve"))
        self.wind_enable_checkBox.setText(_translate("mainWindow", "Enabled"))
        self.label_137.setText(_translate("mainWindow", "kW"))
        self.label_164.setText(_translate("mainWindow", "Land usage rate"))
        self.label_166.setText(_translate("mainWindow", "Land cost"))
        self.label_165.setText(_translate("mainWindow", "km^2 / kW"))
        self.label_167.setText(_translate("mainWindow", "€ / km^2"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("mainWindow", "Wind farm"))
        self.label_118.setText(_translate("mainWindow", "%"))
        self.label_126.setText(_translate("mainWindow", "Years"))
        self.label_128.setText(_translate("mainWindow", "Discharge efficiency"))
        self.label_116.setText(_translate("mainWindow", "%"))
        self.label_120.setText(_translate("mainWindow", "Charge efficiency"))
        self.label_145.setText(_translate("mainWindow", "%"))
        self.label_127.setText(_translate("mainWindow", "Maximum state of charge"))
        self.label_144.setText(_translate("mainWindow", "Minimum state of charge"))
        self.label_122.setText(_translate("mainWindow", "%"))
        self.label_124.setText(_translate("mainWindow", "Equipement life"))
        self.label_172.setText(_translate("mainWindow", "Maximum power for sizing"))
        self.label_129.setText(_translate("mainWindow", "%"))
        self.label_119.setText(_translate("mainWindow", "Percentaje of the investment cost to incurr once the live span has passed"))
        self.label_117.setText(_translate("mainWindow", "%"))
        self.label_123.setText(_translate("mainWindow", "Maintenence cost as % of the investment cost"))
        self.label_175.setText(_translate("mainWindow", "kW"))
        self.label_125.setText(_translate("mainWindow", "Cost per installed kWh"))
        self.label_121.setText(_translate("mainWindow", "€/kWh"))
        self.label_174.setText(_translate("mainWindow", "kW"))
        self.label_173.setText(_translate("mainWindow", "Minimum power for sizing"))
        self.storage_enable_checkBox.setText(_translate("mainWindow", "Enabled"))
        self.label_178.setText(_translate("mainWindow", "Land cost"))
        self.label_177.setText(_translate("mainWindow", "km^2 / kW"))
        self.label_176.setText(_translate("mainWindow", "Land usage rate"))
        self.label_179.setText(_translate("mainWindow", "€ / km^2"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("mainWindow", "Storage"))
        self.label_143.setText(_translate("mainWindow", "kW"))
        self.label_142.setText(_translate("mainWindow", "SPOT market prices"))
        self.label_136.setText(_translate("mainWindow", "€/kWh"))
        self.secondary_price_plot_pushButton.setText(_translate("mainWindow", "Plot"))
        self.label_135.setText(_translate("mainWindow", "€/kWh"))
        self.label_139.setText(_translate("mainWindow", "Secondary reserve market prices"))
        self.grid_enable_checkBox.setText(_translate("mainWindow", "Enabled"))
        self.label_141.setText(_translate("mainWindow", "Connection power"))
        self.spot_price_pushButton.setText(_translate("mainWindow", "Plot"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("mainWindow", "Grid connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("mainWindow", "Desalination plant"))
        self.groupBox_6.setTitle(_translate("mainWindow", "Optimization"))
        self.label_29.setText(_translate("mainWindow", "Objective to minimize"))
        self.size_simulate_pushButton.setText(_translate("mainWindow", "Size facilities"))
        self.label_28.setText(_translate("mainWindow", "Max. Iterations"))
        self.label.setText(_translate("mainWindow", "Start date"))
        self.groupBox_21.setTitle(_translate("mainWindow", "Simulated options sorted by the objective value"))
        self.analyze_selected_pushButton.setText(_translate("mainWindow", "Analyze selected >>"))
        self.plot_results_pushButton.setText(_translate("mainWindow", "Plot"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("mainWindow", "Plot"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("mainWindow", "Report"))
        self.label_36.setText(_translate("mainWindow", "LCOE Sensitivity (Investment rate vs. years of investment)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("mainWindow", "Economic sensitivty"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("mainWindow", "Cash flow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SimulationTab), _translate("mainWindow", "Simulation"))
        self.progress_label.setText(_translate("mainWindow", "Progress..."))
        self.cancel_pushButton.setText(_translate("mainWindow", "Cancel"))
        self.menuProject.setTitle(_translate("mainWindow", "Project"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionOpen_file.setText(_translate("mainWindow", "Open file"))
        self.actionOpen_file.setShortcut(_translate("mainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionNew_project.setText(_translate("mainWindow", "New project"))
        self.actionNew_project.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionDiagram.setText(_translate("mainWindow", "Diagram"))

from .matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

